name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "NUXT_PUBLIC_TEST=${{ secrets.NUXT_PUBLIC_TEST }}" >> .env
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: yarn
        run: yarn
      - name: Build
        id: build
        run: yarn generate
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 sync ./dist s3://nuxt3-env-test --exact-timestamps --delete
